#!/bin/sh

WORKING_DIR=/opt/tg-housing-service/

if [ "${DEPLOY_MODE}" != "CI" ]
  then
    echo "=== reading $(pwd)/.env file ==="
    export $(cat .env | grep -v ^# | xargs)
fi

echo "=== pulling image ${REGISTRY_URL}/${REGISTRY_SERVICE_NAME}:last ==="
docker pull ${REGISTRY_URL}/${REGISTRY_SERVICE_NAME}:last

echo "=== restarting service ==="
systemctl service tg-housing restart

echo "=== clearing ==="
echo y | docker image prune -a

echo "=== check status ==="
systemctl service tg-housing status
